apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1

  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
        - name: mongodb
          image: mongo:6

          ports:
            - containerPort: 27017

          # MongoDB membaca username/password
          # dari file Secret yang di-mount.
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD

          volumeMounts:
            # Persistent storage MongoDB.
            - name: mongo-storage
              mountPath: /data/db

            # ConfigMap sebagai directory /config.
            - name: mongo-config
              mountPath: /config

            # Secret sebagai file credential.
            - name: mongo-credentials
              mountPath: /etc/mongo-credentials
              readOnly: true

      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

        - name: mongo-config
          configMap:
            name: mongo-configmap

        - name: mongo-credentials
          secret:
            secretName: mongo-secret
