apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
spec:
  type: NodePort

  selector:
    app: karsajobs-ui

  ports:
    - name: http
      port: 8000
      targetPort: 8000

      # Port frontend yang dapat diakses dari luar cluster.
      nodePort: 30081
